CREATE TABLE [dbo].[AppUser]
(
	[USER_ID] BIGINT NOT NULL PRIMARY KEY identity(1000, 1), 
    [USER_NAME] VARCHAR(30) NULL, 
    [PASSWORD] VARCHAR(30) NULL, 
    [TITLE] VARCHAR(30) NULL DEFAULT N'医生', 
    [REAL_NAME] VARCHAR(30) NULL, 
    [CONTACT_PHONE] VARCHAR(20) NULL, 
    [CONTACT_ADDR] VARCHAR(200) NULL, 
    [URGENT_CONTACT_PERSON] VARCHAR(50) NULL, 
    [URGENT_CONTACT_PHONE] VARCHAR(50) NULL, 
    [HOSPITAL_NAME] VARCHAR(50) NULL, 
    [CREATE_DATE] DATETIME2 NULL DEFAULT GETDATE(), 
    [APPROVE_FLAG] BIT NULL DEFAULT 0
)
